### ISSUE TITLE
Consider hosting helm charts with the help of chart-releaser and Github

### ISSUE THREAD

**Issue by baluchicken** [pravega/zookeeper-operator#213]
### Description

I propose to host helm charts with the help of the [chart-release](https://github.com/helm/chart-releaser).
This is a simple tool which allows to use github as the source of the helm chart.
It does not require any additional chart-museum, all it need is an index file which contains the information from the various versions of the chart.

### Importance

As of today, to install Pravega's zookeeper operator and a zookeeper cluster via helm, the repo have to be cloned on my local machine. This feature ease up the process for this, since all can be do via helm update and helm install without cloning the repo.

**Comment by derekm** [comment]
@baluchicken,

@SrishT is leading the refactor of our https://github.com/pravega/charts repo as a Helm charts release artifact repository (it was previously a mostly-abandoned monorepo for charts). It will look similar to https://github.com/srisht/charts-test and will live at charts.pravega.io.

This blog shows the process of checking out git repos that you describe: http://blog.pravega.io/2020/06/20/deploying-pravega-in-kubernetes/

We will soon be able to update that blog to use a Helm repo instead of a sequence of git checkouts.

If you'd like to help review Srishti's work, see her charts-test setup and the short wiki here: https://github.com/pravega/charts/wiki/Release-Process

Thanks!

**Comment by SrishT** [comment]
From version 0.2.8 onwards, zookeeper charts for the released zookeeper versions will be available in https://charts.pravega.io/. The charts for version 0.2.8 are already available here.
