### ISSUE TITLE
zk operator bug

### ISSUE THREAD

**Issue by lengrongfu** [pravega/zookeeper-operator#288]
### Description
I started to create a cluster with 5 nodes, and it was created successfully. Later, when I changed to 3, 2 pods could not be deleted normally, and the operator reported an error.

![image](https://user-images.githubusercontent.com/15009201/104128181-0265d400-53a1-11eb-9d73-35daf1e5017f.png)

![image](https://user-images.githubusercontent.com/15009201/104128196-17dafe00-53a1-11eb-887b-1bcfe0a2a760.png)

**Comment by lengrongfu** [comment]
I think the `err` type should be judged here.
![image](https://user-images.githubusercontent.com/15009201/104128729-3098e300-53a4-11eb-92bf-36285941b2ab.png)

**Comment by anishakj** [comment]
@lengrongfu How you performed scale down, Is it by using `kubectl edit zookeepercluster`

**Comment by lengrongfu** [comment]
The scaling is triggered by modifying the value of the `replicas` field in the YAML file.
![image](https://user-images.githubusercontent.com/15009201/104147760-9c159b80-540a-11eb-9f8f-a3bf62c452fb.png)

**Comment by lengrongfu** [comment]
@anishakj hi, do you think this is the problem? If it is a problem, please merge this pr, if not, please close.

**Comment by anishakj** [comment]
> @anishakj hi, do you think this is the problem? If it is a problem, please merge this pr, if not, please close.

After editting the yaml did u perform `kubectl apply`. We didnt see this issue in our environments. Which environment are you using ?

**Comment by lengrongfu** [comment]
Yes, `kubectl apply` is executed, and it is currently in the development environment.

**Comment by maddisondavid** [comment]
While I agree that the code changes would handle the situation where the Meta was already and need to be updated, I'm confused how the code got into this state.  The originating call to `CreateNode` must have come from `reconcileClusterStatus`
https://github.com/pravega/zookeeper-operator/blame/b875bba3b2b69953ec428e7edbbd51592c188aaf/pkg/controller/zookeepercluster/zookeepercluster_controller.go#L552
```
	if instance.Spec.Replicas == instance.Status.ReadyReplicas && (!instance.Status.MetaRootCreated) {
```

However, if the cluster had already deployed then `MetaRootCreated` should be `true` and therefore it shouldn't have attempted to create the root.  Do you have the output from `kubectl get ZookeeperCluster zookeeper -n zookeeper-dev -o=yaml` so that we can see the `status`?

**Comment by anishakj** [comment]
@lengrongfu  Could you please paste the output of above command?

**Comment by anishakj** [comment]
@lengrongfu   Any updates on the query?

**Comment by anishakj** [comment]
Closing this, as there is no response from submitter. Please feel free to reopen if this issue is seen again
