### ISSUE TITLE
Allow offline use

### ISSUE THREAD

**Issue by zanoubia** [pravega/zookeeper-operator#68]
Hello,

In an offline env where we have a private registry (usually mirroring dockerhub)

- [ ] Add a env var to dockerfile to set the registry to use for emccorp/zookeeper image., which will allow to build a custom image without changing the code

or/and

- [ ] make the registry to use in env variables of the operator (idk if possible)

Thank you

**Comment by fpj** [comment]
@pbelgundi why is this issue invalid? I'm actually not sure I fully understand the recommendation in the description. I understand that the goal is to enable the use of a private registry.

**Comment by pbelgundi** [comment]
@fpj marked this as invalid because from issue description it wasn't clear to me as to why this is needed and how it helps?
I think the ask was to use an environment-variable in the [Dockerfile ](https://github.com/pravega/zookeeper-operator/blob/master/docker/Dockerfile#L17) for zk base image instead of the current hard-coded value. 
The startup scripts and other code we have, is tested for a specific base image and I don't see why we would want to change that to a variable.

**Comment by pbelgundi** [comment]
A different repository and image can be specified via charts using the image tag:
https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper/templates/zookeeper.yaml#L8

**Comment by anishakj** [comment]
Closing this issue as the requirement looks irrelevant.
